services:
  back-end-cc-server:
    build:
      context: back-end/cc-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://34.72.229.139:3306/coffee_coder_db
      DB_USERNAME: root
      DB_PASSWORD: go!team$${11-59}ers
  back-end-mock-server:
    build:
      context: back-end/mock-server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      DB_URL: jdbc:mysql://34.72.229.139:3306/mock_csulb_db
      DB_USERNAME: root
      DB_PASSWORD: go!team$${11-59}ers
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - back-end-cc-server
      - back-end-mock-server